version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:latest
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: finalne
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: admin
volumes:
    persistent:
